version: '3'

services:
  api:
    container_name: api_container
    build:
      context: "../"
      dockerfile: docker-django-backend/Dockerfile
      args:
          GS_CREDENTIALS_JSON: ${GS_CREDENTIALS_JSON}
    environment:
      - SECRET_KEY=${SECRET_KEY?Missing SECRET_KEY}
      - MASTER_EMAIL=${MASTER_EMAIL?Missing MASTER_EMAIL}
      - MASTER_PASSWORD=${MASTER_PASSWORD?Missing MASTER_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE?Missing MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER?Missing MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD?Missing MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST?Missing MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT?Missing MYSQL_PORT}
      - GS_CREDENTIALS_JSON=${GS_CREDENTIALS_JSON?Missing GS_CREDENTIALS_JSON}
      - GS_PROJECT_ID=${GS_PROJECT_ID?Missing GS_PROJECT_ID}
      - GS_BUCKET_NAME=${GS_BUCKET_NAME?Missing GS_BUCKET_NAME}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER?Missing EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD?MIssing EMAIL_HOST_PASSWORD}
      - PYTHONUNBUFFERED=1
      - PRODUCTION_ENV=True
  django:
    image: django:latest
    container_name: django_container
    extends:
      service: api
    command: ./scripts/start_server.sh
    ports:
      - 5000:5000
    restart: always
