version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db_container
    command: [mysqld, --max-connections=1000, --wait_timeout=28800]
    volumes:
      - ./persistence/mysql:/var/lib/mysql
    ports:
      - ${MYSQL_EXTERNAL_PORT}:${MYSQL_INTERNAL_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD?Missing MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER?Missing MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD?Missing MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE?Missing MYSQL_DATABASE}
    restart: always

  api:
    container_name: api_container
    volumes:
      - ./project:/backend/project
    build:
      context: "../"
      dockerfile: docker-django-backend/dev.Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - PRODUCTION_ENV=False
      - SECRET_KEY=${SECRET_KEY?Missing SECRET_KEY}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD?Missing EMAIL_HOST_PASSWORD}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER?Missing EMAIL_HOST_USER}
      - MASTER_EMAIL=${MASTER_EMAIL?Missing MASTER_EMAIL}
      - MASTER_PASSWORD=${MASTER_PASSWORD?Missing MASTER_PASSWORD}
      - MYSQL_HOST=db
      - MYSQL_EXTERNAL_PORT=${MYSQL_EXTERNAL_PORT?Missing MYSQL_EXTERNAL_PORT}
      - MYSQL_USER=${MYSQL_USER?Missing MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD?Missing MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE?Missing MYSQL_DATABASE}
  django:
    image: django:latest
    container_name: django_container
    extends:
      service: api
    command: ./scripts/fire_up_server_dev.sh
    ports:
      - ${DJANGO_EXTERNAL_PORT}:${DJANGO_INTERNAL_PORT}
    restart: always
    depends_on:
      - db
