version: '3'

services:
  db:
    image: mysql:latest
    container_name: db_container
    command: [
        mysqld, 
        --performance-schema=off,
        --key_buffer_size=16M,
        --tmp_table_size=1M,
        --innodb_buffer_pool_size=1M,
        --innodb_log_buffer_size=1M,
        --max_connections=25,
        --sort_buffer_size=512M,
        --read_buffer_size=256K,
        --read_rnd_buffer_size=512K
        --join_buffer_size=128K,
        --max-connections=1000, 
        --wait_timeout=28800
    ]
    volumes:
      - ./persistence/mysql:/var/lib/mysql
    ports:
      - ${MYSQL_EXTERNAL_PORT}:${MYSQL_INTERNAL_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD?Missing MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER?Missing MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD?Missing MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE?Missing MYSQL_DATABASE}
    restart: always
  api:
    container_name: api_container
    build:
      context: "../"
      dockerfile: docker-django-backend/prod.Dockerfile
      network: host
      args:
          GS_CREDENTIALS_JSON: ${GS_CREDENTIALS_JSON}
    environment:
      - SECRET_KEY=${SECRET_KEY?Missing SECRET_KEY}
      - MASTER_EMAIL=${MASTER_EMAIL?Missing MASTER_EMAIL}
      - MASTER_PASSWORD=${MASTER_PASSWORD?Missing MASTER_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE?Missing MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER?Missing MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD?Missing MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST?Missing MYSQL_HOST}
      - MYSQL_EXTERNAL_PORT=${MYSQL_EXTERNAL_PORT?Missing MYSQL_EXTERNAL_PORT}
      - GS_CREDENTIALS_JSON=${GS_CREDENTIALS_JSON?Missing GS_CREDENTIALS_JSON}
      - GS_PROJECT_ID=${GS_PROJECT_ID?Missing GS_PROJECT_ID}
      - GS_BUCKET_NAME=${GS_BUCKET_NAME?Missing GS_BUCKET_NAME}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER?Missing EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD?Missing EMAIL_HOST_PASSWORD}
      - PYTHONUNBUFFERED=1
      - PRODUCTION_ENV=True
      - LOCAL_RUN=False
  django:
    image: django:latest
    container_name: django_container
    extends:
      service: api
    command: ./scripts/start_server.sh
    ports:
      - ${DJANGO_EXTERNAL_PORT}:${DJANGO_INTERNAL_PORT}
    restart: always
