# Generated by Django 3.2.9 on 2021-12-31 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
