# Generated by Django 4.0.1 on 2022-02-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='static/default_avatar.png', upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
