# Generated by Django 4.0.1 on 2022-03-19 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220319_1050'),
    ]

    operations = [
    ]
