# Generated by Django 4.0.1 on 2022-04-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220319_1050'),
    ]

    operations = [
    ]
