# Generated by Django 4.0.1 on 2022-04-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220402_1202'),
    ]

    operations = [
    ]
