# Generated by Django 3.1.3 on 2020-12-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covid',
            name='count',
        ),
        migrations.AddField(
            model_name='covid',
            name='cases',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='active_cases',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='cases_cumulative',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='deaths',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='deaths_cumulative',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='hospitalized',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='on_quarantine',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='on_supervision',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='recoveries',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='recoveries_cumulative',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='respirators',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='covid',
            name='used_beds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
