# Generated by Django 3.1.3 on 2020-12-23 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201223_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidCalcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases_daily_increase', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('cases_cumulative_increase', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('deaths_daily_increase', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('deaths_cumulative_increase', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CovidStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, null=True, unique=True)),
                ('cases_daily', models.IntegerField(blank=True, default=0, null=True)),
                ('cases_cumulative', models.IntegerField(blank=True, default=0, null=True)),
                ('deaths_daily', models.IntegerField(blank=True, default=0, null=True)),
                ('deaths_cumulative', models.IntegerField(blank=True, default=0, null=True)),
                ('recoveries_daily', models.IntegerField(blank=True, default=0, null=True)),
                ('recoveries_cumulative', models.IntegerField(blank=True, default=0, null=True)),
                ('active_cases', models.IntegerField(blank=True, default=0, null=True)),
                ('hospitalized', models.IntegerField(blank=True, default=0, null=True)),
                ('on_quarantine', models.IntegerField(blank=True, default=0, null=True)),
                ('on_supervision', models.IntegerField(blank=True, default=0, null=True)),
                ('used_beds', models.IntegerField(blank=True, default=0, null=True)),
                ('respirators', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='COVID',
        ),
    ]
