version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db_container
    command: [mysqld, --max-connections=1000, --wait_timeout=28800]
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=backend_db
    restart: always
  api:
    container_name: api_container
    volumes:
      - ./project:/backend/project
    build:
      context: ..
      dockerfile: api/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=${SECRET_KEY?Missing SECRET_KEY}
      - MASTER_USERNAME=${MASTER_USERNAME?Missing MASTER_USERNAME}
      - MASTER_PASSWORD=${MASTER_PASSWORD?Missing MASTER_PASSWORD}
      - MASTER_EMAIL=${MASTER_EMAIL?Missing MASTER_EMAIL}
      - PRODUCTION_ENV=False

  redis:
    image: redis
    container_name: redis_container
    restart: always

  celery-worker:
    container_name: celery_worker_container
    extends:
      service: api
    command: ./scripts/start_celery_worker.sh
    depends_on:
      - redis

  celery-beat:
    container_name: celery_beat_container
    extends:
      service: api
    command: ./scripts/start_celery_beat.sh
    depends_on:
      - redis
      - celery-worker

  django:
    image: django:latest
    container_name: django_container
    extends:
      service: api
    command: ./scripts/fire_up_server_dev.sh
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - db
      - redis
      - celery-worker
      - celery-beat