name: Deploy To Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Will ssh into api-droplet, pull current code and docker-compose up
    runs-on: ubuntu-latest

    steps:
      - name: Deploy new version of server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          
          script: |
            cd docker-django-backend
            ls -la
            git pull origin main
            ./up-dev.sh
