name: Deploy To Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy new version of server
    runs-on: ubuntu-latest

    steps:
      - name: Deploy new version of server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}}
          
          script: |
            cd docker-django-backend
            git pull origin main
            ./up-service.sh --env prod
